import { t } from "elysia";

export const twilioRequestBody = t.Object({
  Called: t.String(),
  ToState: t.String(),
  CallerCountry: t.String(),
  Direction: t.String(),
  SpeechResult: t.String(),
  CallerState: t.String(),
  Language: t.String(),
  Confidence: t.String(),
  ToZip: t.String(),
  CallSid: t.String(),
  To: t.String(),
  CallerZip: t.String(),
  ToCountry: t.String(),
  ApiVersion: t.String(),
  CalledZip: t.String(),
  CallStatus: t.String(),
  CalledCity: t.String(),
  From: t.String(),
  AccountSid: t.String(),
  CalledCountry: t.String(),
  CallerCity: t.String(),
  Caller: t.String(),
  FromCountry: t.String(),
  ToCity: t.String(),
  FromCity: t.String(),
  CalledState: t.String(),
  FromZip: t.String(),
  FromState: t.String(),
});
